apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: shoppingapi-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shoppingapi-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
  targetCPUUtilizationPercentage: 50

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: shoppingclient-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shoppingclient-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
  targetCPUUtilizationPercentage: 50

